### PR TITLE
10-Customizing-Lock

### PR DESCRIPTION
**Pull request by pablolvillar**
Please, download this source code to perform code review & check everything works as expected.

### CODE REVIEW

**Comment by sebacancinos** [comment]
+1 @ntotten @mariapaktiti

**Comment by pablolvillar** [comment]
@mpaktiti ^

**Comment by mpaktiti** [comment]
Hi @pablolvillar, we will get back to you once our mobile engineers review this. Thanks.

^ @chenkie

**Comment by pablolvillar** [comment]
`README.md` pending review @sebacancinos

**Comment by sebacancinos** [comment]
+1 @chenkie

**Pull request merged**
