### PR TITLE
05-Linking-Accounts

### PR DESCRIPTION
**Pull request by pablolvillar**
- Added 05-Linking-Accounts sample project, finished.
- ⚠️ This branch has been worked on top of the previous ones. It's recommended to merge the previous ones first.

### CODE REVIEW

**Comment by sebacancinos** [comment]
+1 @ntotten

**Comment by pablolvillar** [comment]
`README.md` pending review @sebacancinos

**Comment by sebacancinos** [comment]
+1 @chenkie

**Comment by chenkie** [comment]
@pablolvillar can you address the conflicts here?

**Comment by pablolvillar** [comment]
Solved

**Pull request merged**
