### PR TITLE
08-Calling-APIs

### PR DESCRIPTION
**Pull request by pablolvillar**
- Added 08-Calling-APIs sample project, working.

### CODE REVIEW

**Comment by sebacancinos** [comment]
+1 @ntotten @mariapaktiti

**Comment by pablolvillar** [comment]
@mpaktiti ^

**Comment by mpaktiti** [comment]
Hi @pablolvillar, we will get back to you once our mobile engineers review this. Thanks.

^ @chenkie

**Comment by pablolvillar** [comment]
`README.md` pending review @sebacancinos

**Comment by sebacancinos** [comment]
+1 @chenkie

**Pull request merged**
