### PR TITLE
04-User-Profile

### PR DESCRIPTION
**Pull request by pablolvillar**
- Added user profile sample project.
- Includes an extra screen with a more complete user profile (with metadata, such as `firstName`, `lastName` and `country`, including the ability to edit the fields and save them, by sending a `patch` request via the [Auth0.swift](https://github.com/auth0/Auth0.swift) toolkit.
- ⚠️ This PR includes the previous sample projects, so it's recommendable not to merge this one till the rest have been merged.
- ⚠️ The update profile response is yielding a `401` (unauthorized). It seems it's about an issue in the library @hzalaz is working on that. ⛔️  **Do not merge this PR yet.** It's been created only for reviewing purposes.

### CODE REVIEW

**Comment by pablolvillar** [comment]
This is ready for review @sebacancinos

**Comment by sebacancinos** [comment]
+1 @ntotten

**Comment by pablolvillar** [comment]
`README.md` pending review @sebacancinos

**Comment by chenkie** [comment]
@pablolvillar can you address the conflicts here?

**Comment by pablolvillar** [comment]
Solved

**Pull request merged**
