### PR TITLE
02-Custom-Login

### PR DESCRIPTION
**Pull request by pablolvillar**
- Added Custom Login sample project.
- This project uses [Auth0 toolkit](https://github.com/auth0/Auth0.swift) library instead of [Lock](https://github.com/auth0/Lock.iOS-OSX).
- Contains screens for Login, Sign Up, and a very basic User Profile screen.

### CODE REVIEW

**Comment by sebacancinos** [comment]
+1 @ntotten

**Comment by pablolvillar** [comment]
@mpaktiti ^

**Comment by mpaktiti** [comment]
Hi @pablolvillar, we will get back to you once our mobile engineers review this. Thanks.

^ @chenkie

**Comment by pablolvillar** [comment]
`README.md` pending review @sebacancinos

**Comment by sebacancinos** [comment]
+1 @chenkie to the readme

**Pull request merged**
