### PR TITLE
01-Login

### PR DESCRIPTION
**Pull request by pablolvillar**
- Copied **00-Starter-Seed** project and worked on Login Quickstart sample onto it.
- Added `Cocoapods`(now we use `.xcworkspace`).
- Integrated all `auth0` login functionality with `Lock` library.
- Left auth0 `Info.plist` keys with placeholders so that they are automagically filled with users' keys when they download the project from the documentation website. ← I'm gonna need a reminder for this one everytime I finish testing, before Pull Requesting (maybe we can add a default checklist or something)
- ⚠️  We might want to check whether `.gitignore` is working properly. It appears it isn't, I've seen some `xcuserstate` and the like around there in my `git status`es... It could be due to having subfolders and not working at the root level (as I use to with just a single project/workspace) @hzalaz please check this.

### CODE REVIEW

**Comment by sebacancinos** [comment]
+1

**Comment by pablolvillar** [comment]
@mpaktiti ^

**Comment by mpaktiti** [comment]
Hi @pablolvillar, we will get back to you once our mobile engineers review this. Thanks.

^ @chenkie

**Comment by pablolvillar** [comment]
`README.md` pending review @sebacancinos

**Comment by sebacancinos** [comment]
I don't think you should make this comment on the readme:
"This is a very simple approach to do so. You'll find later on, in further sample projects, that this strategy is replaced by using a `SessionManager` class, which avoids updating inconsistencies among view controllers."

I'd rather comment on the following readme, when SessionManager is implemented, that it's a better solution than the previous method of passing the profile on the prepareForSegue

**Comment by sebacancinos** [comment]
the prepareforSegue snippet has an extra tab, align it to the left

**Pull request merged**
